## Chapter 2
### NumPy Basics

#### 2.1 Creating arrays

In [1]:
import numpy as np

In [6]:
a = np.arange(10) # like range() but function returns a NumPy array
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b = np.arange(1, 5, 0.5) # arguments are (start, stop, step)
b

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [8]:
c = np.linspace(-np.pi, np.pi, 5) # (start, stop, num_points)
c

array([-3.14159265, -1.57079633,  0.        ,  1.57079633,  3.14159265])

In [9]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [10]:
# diaganal with offset from the main diagonal
np.diag([1,2,3],k=2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
c.dtype

dtype('float64')

In [14]:
cc = np.arange(20, dtype=np.float128)

In [15]:
cc.dtype

dtype('float128')

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 2.2 Converting sequences (lists etc.) into arrays

In [18]:
l = list(range(10))
d = np.array(l)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
l2 = [[1, 3, 5], [2, 4, 6], [3, 30, 300]]
d2 = np.array(l2)
d2

array([[  1,   3,   5],
       [  2,   4,   6],
       [  3,  30, 300]])

In [20]:
d2.dtype

dtype('int64')

In [21]:
d2.shape

(3, 3)

In [22]:
d2.shape[0]

3

#### 2.3 Simple indexing and slicing

In [23]:
d2[1, 2] # row 1, column 2 ... i.e. second row, third column

6

In [24]:
d2[1, :]

array([2, 4, 6])

In [25]:
d2[:, 2] # column 2, all rows

array([  5,   6, 300])

In [26]:
c = d2[:, 2]
c

array([  5,   6, 300])

In [29]:
d2[2, 2] = 5000
d2

array([[   1,    3,    5],
       [   2,    4,    6],
       [   3,   30, 5000]])

In [30]:
c

array([   5,    6, 5000])

In [31]:
d3 = np.arange(12)
d3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
# We can use reshape() to change array dimensions
d4 = d3.reshape(3,4)
d4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 2.4 Fancy indexing

In [36]:
d_squared = d**2
d_squared

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
# Get the first, thurd and last item from the list
ind = [0, 2, -1] 
d_squared[ind]

array([ 0,  4, 81])

In [39]:
rows = [0, 2]
d2_squared[rows, :]

NameError: name 'd2_squared' is not defined